updated version allowing multiple templates

diff --git a/vm-create b/vm-create
--- a/vm-create
+++ b/vm-create
@@ -1,38 +1,109 @@
 #!/bin/bash
 
-NAME=$1
-NR=$(echo $NAME | egrep -o '[0-9][0-9]$')
-P=$$
-LANG=C
-TPD=/srv/vm/datastores/templates
-VMD=/srv/vm/datastores/vms
+########################
+#        CONFIG
+########################
 
-if [ $# -lt 3 ] ; then 
-  MEMORY=3145728
-  VCPU=2
-else
-  MEMORY=$3
-  VCPU=$2
+min_vm_nr=10
+max_vm_nr=40
+
+# paths
+dir_template=/srv/vm/datastores/templates
+dir_vm=/srv/vm/datastores/vms
+dir_tmp=/tmp
+
+# default values
+vm_template="cos"
+vm_vcpu=2
+vm_memory=2097152
+vm_nr=0
+
+# Dist <> MAC table
+declare -A template2mac
+template2mac['cos']='00'
+template2mac['rhel']='01'
+
+
+########################
+#  Argument Processing
+########################
+
+
+for i in "$@"
+do
+case $i in
+    --vcpu=*)
+      vm_vcpu="${i#*=}"
+    shift
+    ;;
+    --memory=*)
+      vm_memory="${i#*=}"
+    shift
+    ;;
+    --nr=*)
+      vm_nr="${i#*=}"
+    shift
+    ;;
+    --template=*)
+      vm_template="${i#*=}"
+    shift
+    ;;
+    --help=*)
+      echo "usage bla bla"
+
+      exit;
+    shift
+    ;;
+    *)
+        if [[ $i =~ ^[a-z]+[0-9]{2}$ ]]; then
+            vm_template="$(echo $i | sed -E 's;([a-z]+)([0-9]{2});\1;')"
+            vm_nr="$(echo $i | sed -E 's;([a-z]+)([0-9]{2});\2;')"
+        else
+            vm_template=$i
+        fi
+    ;;
+esac
+done
+
+
+########################
+#        SCRIPT
+########################
+
+# Only if no NR provided
+if [[ vm_nr == 0 ]] ; then
+  # find next free VM name
+  for i in {$min_vm_nr..$max_vm_nr} ; do if ! virsh list --all --title | grep "$vm_template$i" > /dev/null ; then echo $i ; break ; fi ; done
 fi
 
+# gnerate full name
+$vm_name="$vm_template$vm_nr"
 
+# check if VM is free
+virsh list --all | grep "$vm_name" && (echo ERROR: "$vm_name" exists ; kill -9 $P )
 
-echo $NAME | egrep -q '^vm[0-9][0-9]$' || (echo Usage: $(basename $0) vmNN ; kill -9 $P )
-virsh list --all | grep $NAME && (echo ERROR: $NAME exists ; kill -9 $P )
-echo "INFO: Create CentOS 8 VM: $NAME"
+echo "INFO: Creating $vm_template VM: $vm_name"
 
-  set -e
-  MYUUID=$(uuidgen)
-  cd $TPD
-  cp -av template_cos8.qcow2 $VMD/$NAME.qcow2
-  sed "s/__NAME__/$NAME/g" template_cos8.xml > $NAME.xml
-  sed -i "s/__NR__/$NR/g" $NAME.xml
-  sed -i "s/__UUID__/$MYUUID/g" $NAME.xml
-  sed -i "s/__DISK1__/$NAME.qcow2/g" $NAME.xml
-  sed -i "s/__MEMORY__/$MEMORY/g" $NAME.xml
-  sed -i "s/__VCPU__/$VCPU/g" $NAME.xml
- # sed -i "s/__DISK2__/${NAME}_2.qcow2/g" $NAME.xml
-  virsh define $NAME.xml > /dev/null
-  rm -f $NAME.xml
-  virsh start $NAME
+# "Failsave"
+set -e
 
+# generate UUID
+vm_uuid=$(uuidgen)
+
+# Copy Disk
+cp -av $dir_template/template_$vm_template.qcow2 $dir_vm/$vm_name.qcow2
+
+# Prepare Import XML
+sed "s/__NAME__/$vm_name/g" $dir_template/template_$vm_template.xml > $dir_tmp/$vm_name.xml
+sed -i "s/__NR__/$vm_nr/g" $dir_tmp/$vm_name.xml
+sed -i "s/__UUID__/$vm_uuid/g" $dir_tmp/$vm_name.xml
+sed -i "s/__DISK1__/$vm_name.qcow2/g" $dir_tmp/$vm_name.xml
+sed -i "s/__MEMORY__/$vm_memory/g" $dir_tmp/$vm_name.xml
+sed -i "s/__VCPU__/$vm_vcpu/g" $dir_tmp/$vm_name.xml
+sed -i "s/__MAC__/00:00:00:00:${template2mac[$vm_template]}:$vm_nr/g" $dir_tmp/$vm_name.xml
+
+# define new VM
+virsh define $dir_tmp/$vm_name.xml > /dev/null
+
+# start VM
+virsh start $vm_name
